SET( CTEST_PROJECT_NAME "FARSA" )
SET( CTEST_NIGHTLY_START_TIME "00:00:00 CET" )

SET( CTEST_DROP_METHOD "http" )
SET( CTEST_DROP_SITE "192.168.0.1" )
SET( CTEST_DROP_LOCATION "/CDash/submit.php?project=${CTEST_PROJECT_NAME}" )
SET( CTEST_DROP_SITE_CDASH TRUE )
