# This file contains variables used to customize the behaviour of CTest
SET( CTEST_CUSTOM_MAXIMUM_NUMBER_OF_ERRORS 1000 )
SET( CTEST_CUSTOM_MAXIMUM_NUMBER_OF_WARNINGS 1000 )
SET( CTEST_CUSTOM_MAXIMUM_PASSED_TEST_OUTPUT_SIZE 1048576 )
SET( CTEST_CUSTOM_MAXIMUM_FAILED_TEST_OUTPUT_SIZE 1048576 )
